### PR TITLE
Do training without vizier

### PR DESCRIPTION
**Pull request by panford**
These changes allow training on vertex ai with default hyperparameters and no vizier hyperparameter tuning.
The metrics recorded when doing a no vizier training is logged to a Tensorboard Instance.

### CODE REVIEW

**Comment by jzxu** [comment]
Hi Kobby, thank you for making this PR. Overall it looks good to me. One main question: does the code create Tensorboard instances in order to visualize the experiment metrics? I ask because for some reason, Tensorboard instances on Cloud cost money to keep running, and if you have multiple tensorboard instances that you don't shut down for several months, the cost adds up.

**Comment by panford** [comment]
Hi @jzxu 
Yes, the tensorboard instances are created only to visualize the experiment metrics. I'm aware of the high costs involved in creating and running a vertex ai tensorboard instance. I usually delete them from the GCP console after doing my analysis to avoid recurring charges.

**Comment by panford** [comment]
Hi @jzxu 
I have undone the vertex ai tensorboard inclusion. 
I will create a separate PR to work on tracking experiment metrics by running tensorboard from local terminal.

Thank you

**Comment by jzxu** [comment]
> Hi @jzxu I have undone the vertex ai tensorboard inclusion. I will create a separate PR to work on tracking experiment metrics by running tensorboard from local terminal.
> 
> Thank you

Thanks! I've kicked off the internal review process.

**Comment by jzxu** [comment]
Hi Kobby, is this PR now obsolete now that PR202 has been merged? If so can you please close this? Thanks!

**Pull request closed without merging**
